expr_name: n4_exp
log_dir: ./logs             #log directory
seed: 0
device_num: 1

Environment:
  Entities:
    - entity_name: 'government'
      entity_args:
        n: 1            #number of government
        action_shape: 5

    - entity_name: 'household'
      entity_args:
        n: 4
        CRRA: 1
        IFE: 2
        eta: 0
        action_shape: 2
        e_p: 2.2e-6
        e_q: 0.990
        rho_e: 0.982
        sigma_e: 0.200
        super_e: 504.3

  env_core:
    possible_agents: ['government', 'households']
    env_args:
      alpha: 1/3
      year_per_step: 1
      depreciation_rate: 0.06
      consumption_tax_rate: 0.065
      interest_rate: 0.04
      gini_weight: 1
      gov_task: "gdp"  # choices: {"gdp", "gini", "social_welfare", "gdp_gini"}


Trainer:
  n_households: 4
  log_std_min:  -20
  log_std_max:  2
  hidden_size:  128
  cuda: True
  q_lr: 3e-4
  p_lr: 3e-4
  buffer_size:  1e6
  env_name: 'wealth_distribution'
  init_exploration_policy:  'gaussian'
  n_epochs: 1500
  epoch_length: 500
  update_cycles:  10
  target_update_interval: 1
  display_interval: 1
  batch_size: 128
  gamma: 0.975
  tau:  5e-3
  eval_episodes: 10
  init_exploration_steps: 1000
  ppo_tau: 0.95
  ppo_gamma: 0.99
  eps: 1e-5
  update_epoch: 20
  clip: 0.1
  vloss_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  update_freq: 2
  initial_train: 100
  noise_rate: 0.1
  epsilon: 0.1
  save_interval: 100





